# Generated by Django 2.1.7 on 2019-09-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fyi',
            name='head',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='fyi',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
