# Generated by Django 2.1.7 on 2019-09-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_diy'),
    ]

    operations = [
        migrations.AddField(
            model_name='diy',
            name='file',
            field=models.FileField(default='', upload_to='docs/diy'),
        ),
    ]
