# Generated by Django 2.1.7 on 2019-09-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenor',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
