# Generated by Django 2.1.7 on 2019-09-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20190917_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='headcoordinator',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='manager',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
